remote_theme: riggraz/no-style-please
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Craig Moore III
description: Welcome to my site!
show_downloads: false
appearance: "dark"

# No Style, Please! theme from riggraz https://riggraz.dev/no-style-please/